version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - my_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-backups/db-backup:/backup

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - my_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis-backups:/backup

  personal-website:
    #image: abhishekprakash256/personal-website:latest
    image: personal-website-test:latest
    container_name: personal-website
    networks:
      - my_network
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

networks:
  my_network:
    external: true

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  website-data:
    driver: local
