version: '1.0'

services:
  web:
    build: .
    image: my-flask-app:test
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/articles
      - MONGO_URI_2=mongodb://localhost:27017/section
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
