- name: Service Checks
  hosts: ec2
  become: yes

  tasks:  
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result

    - name: Check Redis status
      ansible.builtin.systemd:
        name: redis-server
        state: status
      register: redis_status
      failed_when: redis_status.status.ActiveState != 'active'

    - name: Display Redis status
      ansible.builtin.debug:
        msg: "Redis is {{ redis_status.status.ActiveState }}"
