- name: Service Checks
  hosts: ec2
  become: yes

  tasks:
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result

    
    - name: Check the redis is running 
      shell: systemctl is-active redis-server.serv || true


    