- name: Service Checks
  hosts: ec2
  become: yes

  tasks:  
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result


    - name: Check service status with systemctl
      shell: systemctl is-active redis-server || true
      register: redis_service_status_systemctl  
      ignore_errors: yes

    - name: Print Redis service status
      ansible.builtin.debug:
        msg: "Redis service status is: {{ redis_service_status_systemctl.stdout }}"
  
    - name: Fail if Redis is inactive
      ansible.builtin.fail:
        msg: "Redis service is inactive!"
      when: redis_service_status_systemctl.stdout == "inactive"  