- name: Service Checks
  hosts: ec2
  become: yes

  tasks:
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result

    
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd

