- name: Service Checks
  hosts: ec2
  become: yes

  tasks:
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result

    
    - name: Check if Redis server is running
          ansible.builtin.systemd:
            name: redis-server
            state: status
          register: redis_service_status

        - name: Print Redis server status
          ansible.builtin.debug:
            msg: "Redis server is {{ redis_service_status.status }}"
        
        - name: Fail if Redis server is not running
          ansible.builtin.fail:
            msg: "Redis server is not running"
          when: redis_service_status.status.LoadState != "loaded" or redis_service_status.status.ActiveState != "active"


    