- name: Service Checks
  hosts: ec2
  become: yes

  tasks:  
    - name: Check server is up by pinging localhost
      command: ping -c 4 localhost
      register: ping_result


    - name: Print Redis service facts
      ansible.builtin.debug:
        var: ansible_facts.services['redis-server']

    - name: Fail if Redis is not running
      ansible.builtin.fail:
        msg: "Redis is not running"
      when: ansible_facts.services['redis-server'].state != 'running'