version: '3'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - my_network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --nginx; sleep 12h & wait $${!}; done;'"

networks:
  my_network:
    external: true
