name: Periodic Check For Website

on:
  push:
    branches:
      - periodic-testing
  pull_request:
    branches:
      - periodic-testing

jobs:
  service-checks:  
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini ansible/playbooks/service-test.yml