name: CI/CD Pipeline

stages: 
  - build
  - provision

build:
  stage: build
  image: python:3.11-slim
  before_script:
    - apt-get update
    - apt install ansible -y
    - pip install botocore boto3
    - python3 -m pip install --upgrade --user ansible 
  script:
    - echo "builing machine"

